title: Sense HAT Marble Maze
hero_image: images/banner.png
description: Create a marble maze game on the Sense HAT's LED matrix
of the Sense HAT
original_url: https://raspberrypi.org/learning/sense-hat-marble-maze
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, electronic-components, python, sense-hat
site_areas: projects
hardware: raspberry-pi, electronic-components, sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: What is a marble maze?
- title: Set up the Sense HAT
- title: Draw the maze
- title: Add a marble
- title: Detect pitch and roll
- title: Move the marble
- title: Fix the marble
- title: Make the walls solid
- title: Goal!
- title: "Challenge: improve the maze"