title: Sense HAT Marble Maze
hero_image: images/banner.png
description: Activity to create a marble maze game that can be played on the LED matrix
  of the Sense HAT
original_url: https://raspberrypi.org/learning/sense-hat-marble-maze
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: What is a marble maze?
- title: Set up the Sense HAT
- title: Draw the maze
- title: Add a marble
- title: Detect the pitch and roll
- title: Move the marble
- title: Fixing the code
- title: Handling collisions with the walls
- title: For the win
- title: What Next?
