---
title: Sense HAT Marble Maze
hero_image: images/banner.png
description: Create a marble maze game on the Sense HAT's LED matrix
original_url: https://raspberrypi.org/learning/sense-hat-marble-maze
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, python, sense-hat
site_areas: projects
hardware: electronic-components, sense-hat
software: python
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: What is a marble maze?
- title: Set up the Sense HAT
  completion:
  - engaged
- title: Draw the maze
- title: Add a marble
- title: Detect pitch and roll
- title: Move the marble
- title: Fix the marble
- title: Make the walls solid
- title: Goal!
  completion:
  - internal
- title: 'Challenge: improve the maze'
