title: Sense HAT Marble Maze
hero_image: images/banner.png
description: Create a marble maze game on the Sense HAT's LED matrix
  of the Sense HAT
original_url: https://raspberrypi.org/learning/sense-hat-marble-maze
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: What is a marble maze?
- title: Set up the Sense HAT
- title: Draw the maze
- title: Add a marble
- title: Detect pitch and roll
- title: Move the marble
- title: Fix the marble
- title: Make the walls solid
- title: Goal!
- title: "Challenge: improve the maze"
